spring.application.name=urlshorteningservice
server.port=8080

#MongoDB
# Use the Atlas URI for cloud; comment it out and use host/port for local Docker.
spring.data.mongodb.uri=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
spring.data.mongodb.database=urlshorteningdb

# Custom properties
#  SHORTURL_BASE_URL=https://yourdomain.com
shorturl.base-url=http://localhost:8080